from setuptools import setup, find_packages
  
setup(
    name='Rbbm',
    version='0.0.2',
    url='https://github.com/J-Miao/labelling_explanation',
    author='Author Name',
    author_email='author@gmail.com',
    description='Description of my package',
    packages=find_packages(),
    install_requires=["colorful==0.5.4",
                    "gensim==4.2.0",
                    "ipython==8.6.0",
                    "lark==1.1.3",
                    "lime==0.2.0.1",
                    "matplotlib==3.6.2",
                    "names==0.3.0",
                    "networkx==2.8.6",
                    "nltk==3.7",
                    "numpy==1.23.3",
                    "pandas==1.5.0",
                    "psycopg2_binary==2.9.3",
                    "pyitlib==0.2.2",
                    "pytest==7.2.0",
                    "python_Levenshtein==0.20.8",
                    "requests==2.28.1",
                    "scipy==1.9.1",
                    "setuptools==41.2.0",
                    "SQLAlchemy==1.4.41",
                    "tensorflow",
                    "textblob==0.17.1",
                    "torch",
                    "tqdm==4.64.1",
                    "transformers"],
    entry_points={
        'console_scripts': [
            'rbbm=rbbm_src.main:main',
        ]},
    )